---
#------------------------------------------------------------
# Setup VNC Server
#------------------------------------------------------------

- name:  Install the GUI and VNC Packages
  apt:
    name: xfce4, xfce4-goodies, tightvncserver, expect, firefox
    state: latest
    update_cache: yes

- name: Create .vnc directory
  file:
    path: "{{ user_home_dir }}/.vnc/"
    state: directory
    mode: 0775
  become: yes
  become_user: "{{ linux_user }}"

- name: Copy password script for VNC
  template:
    src: create_password.sh
    dest: "{{ user_home_dir }}/.vnc/pass.sh"
    mode: 0744
  become: yes
  become_user: "{{ linux_user }}"

- name: Run password script for VNC
  shell: ". {{ user_home_dir }}/.vnc/pass.sh"
  become: yes
  become_user: "{{ linux_user }}"

- name: Copy the modified "xstartup" file for VNC
  template:
    src: xstartup.sh
    dest: "{{ user_home_dir }}/.vnc/xstartup"
    mode: 0744
  become: yes
  become_user: "{{ linux_user }}"

- name: Create VNC Server service
  template:
    src: "../templates/vncserver.service"
    dest: /etc/systemd/system/vncserver@.service
    owner: root
    group: root

- name: Ensure that VNC Server service is started with session 1
  service:
    name: vncserver@1
    state: restarted
    enabled: yes
