---
linux_user: "{{ lookup('env', 'LINUX_USER') }}"
user_home_dir: "/home/{{ linux_user }}"
coder_apps_work_dir: "{{ user_home_dir }}/coder-apps"
lets_encrypt_email: "{{ lookup('env', 'EMAIL') }}"
server_domain: "{{ lookup('env', 'SERVER_DOMAIN') }}"
ssh_key_file: "{{ lookup('env', 'SSH_KEY') }}"
repository_url: "{{ lookup('env', 'REPOSITORY_URL') }}"
auth_username: "{{ lookup('env', 'AUTH_USERNAME') }}"
auth_password: "{{ lookup('env', 'AUTH_PASSWORD') }}"
