---
admin_username: root
theia_username: theia
theia_home_dir: "/home/{{ theia_username }}"
theia_work_dir: "{{ theia_home_dir }}/eclipse-theia"
lets_encrypt_email: "{{ lookup('env', 'EMAIL') }}"
theia_domain: "{{ lookup('env', 'THEIA_DOMAIN') }}"
ssh_key_file: "{{ lookup('env', 'SSH_KEY') }}"
repository_url: "{{ lookup('env', 'REPOSITORY_URL') }}"
username: "{{ lookup('env', 'USERNAME') }}"
password: "{{ lookup('env', 'PASSWORD') }}"
