---
#------------------------------------------------------------
# User Setup
#------------------------------------------------------------

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: "Create the main user {{ linux_user }}"
  user:
    name: "{{ linux_user }}"
    comment: Main user
    create_home: yes
    home: "{{ user_home_dir }}"
    groups: [admin, sudo, wheel]
    shell: /usr/bin/bash
    append: yes
    state: present
    skeleton: "/etc/skel"
    password: "{{ linux_password | password_hash('sha512') }}"

- name: Allow SSH connections with password
  replace:
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'
  notify:
  - Reload SSH service

- name: Set authorized key taken from file
  authorized_key:
    user: "{{ linux_user }}"
    state: present
    key: "{{ lookup('file', '{{ ssh_key_file }}') }}"

#------------------------------------------------------------
# Basic Firewall Setup
#------------------------------------------------------------

- name: Allow inbound traffic to OpenSSH
  ufw:
    rule: allow
    name: OpenSSH

- name: Enable UFW
  ufw:
    state: enabled

#------------------------------------------------------------
# Setup Directories
#------------------------------------------------------------

- name: Create a workspace directory if it does not exist
  file:
    path: "{{ workspace_dir }}"
    state: directory
    mode: '0755'
  become: yes
  become_user: "{{ linux_user }}"