---
#------------------------------------------------------------
# Start nginx + Let's Encrypt reverse proxy
#------------------------------------------------------------

- name: Start nginx + SSL docker service
  docker_compose:
    project_src: "{{ coder_apps_work_dir }}"
    files: nginx-proxy-compose.yaml
    state: present
    restarted: yes
  register: output
