---
#------------------------------------------------------------
# Start nginx + Let's Encrypt reverse proxy
#------------------------------------------------------------

- name: Create nginx+SSL Docker configuration
  template:
    src: "../templates/nginx-proxy-compose.yaml"
    dest: "{{ nginx_proxy_compose_file }}"
  become: yes
  become_user: "{{ linux_user }}"
  notify:
    - Restart Docker reverse proxy service

- name: Create nginx+SSL service
  template:
    src: "../templates/docker-reverse-proxy.service"
    dest: /etc/systemd/system/docker-reverse-proxy.service
  notify:
  - Restart Docker reverse proxy service

- name: Create /etc/nginx directory
  file:
    path: "/etc/nginx"
    state: directory

- name: Create proxy.conf file for nginx
  template:
    src: "../templates/proxy.conf"
    dest: /etc/nginx/proxy.conf
  notify:
  - Restart Docker reverse proxy service

- name: Enable nginx+SSL service
  service:
    name: docker-reverse-proxy
    enabled: yes

- name: Make shure that nginx+SSL service is running
  service:
    state: started
    name: docker-reverse-proxy
