---
#------------------------------------------------------------
# Start nginx + Let's Encrypt reverse proxy
#------------------------------------------------------------

- name: Create nginx+SSL service
  template:
    src: "../templates/docker-reverse-proxy.service"
    dest: /etc/systemd/system/docker-reverse-proxy.service
  notify:
  - Restart Docker reverse proxy service

- name: Enable nginx+SSL service
  service:
    name: docker-reverse-proxy
    enabled: yes

- name: Make shure that nginx+SSL service is restarted and running
  service:
    state: restarted
    name: docker-reverse-proxy
