---
#------------------------------------------------------------
# Start Eclipse Theia IDE
#------------------------------------------------------------

- name: Start Eclipse Theia IDE
  docker_compose:
    project_src: "{{ coder_apps_work_dir }}"
    files: eclipse-theia-compose.yaml
    state: present
    restarted: yes
  register: output
