---
#------------------------------------------------------------
# Setup Eclipse Theia IDE
#------------------------------------------------------------

- name: Create Theia Docker configuration
  template:
    src: "../templates/eclipse-theia-compose.yaml"
    dest: "{{ theia_compose_file }}"
  become: yes
  become_user: "{{ linux_user }}"
  notify:
    - Restart Theia service

- name: Setup basic auth password for Theia
  htpasswd:
    path: "/etc/nginx/htpasswd/{{ theia_domain }}"
    name: "{{ auth_username }}"
    password: "{{ auth_password }}"
    owner: root
    group: www-data
    mode: 0644

- name: Create Theia service
  template:
    src: "../templates/theia.service"
    dest: /etc/systemd/system/theia.service
  notify:
    - Restart Theia service

- name: Enable Theia service
  service:
    name: theia
    enabled: yes

- name: Make shure that Theia service is running
  service:
    state: started
    name: theia
