---
- name: Install python for Ubuntu 20
  hosts: all
  gather_facts: no
  pre_tasks:
  - name: Install python for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python3)"
    register: output
    changed_when: output.stdout != ""

- hosts: all
  vars_files:
  - vars/main.yml
  roles:
  - init
#  - system-dependencies
  - repository-setup
#  - security
  - reverse-proxy
  - ihaskell
#  - eclipse-theia
