---
#------------------------------------------------------------
# Checkout repository
#------------------------------------------------------------

- name: Checkout main repository
  git:
    repo: "{{ repository_url }}"
    dest: "{{ theia_work_dir }}"
    update: yes
  become: yes
  become_user: "{{ theia_username }}"

#------------------------------------------------------------
# Environment Setup
#------------------------------------------------------------

- name: generate .env file
  template:
    src: "../templates/.env.template"
    dest: "{{ theia_work_dir }}/.env"
  become: yes
  become_user: "{{ theia_username }}"
