---
#------------------------------------------------------------
# Checkout repository
#------------------------------------------------------------

- name: Checkout main repository
  git:
    repo: "{{ repository_url }}"
    dest: "{{ repo_dir }}"
    update: yes
  become: yes
  become_user: "{{ linux_user }}"
