---
#------------------------------------------------------------
# Destroy the main coder EC2 instance
#------------------------------------------------------------

- name: Get the existing main coder EC2 instance ID
  set_fact: coder_ec2_instance_id="{{ lookup('aws_ssm', '{{ aws_ssm_path }}/state/coder_ec2_instance.id') | default('N/A', true) }}"

- name: Output the existing main coder EC2 instance ID
  ansible.builtin.debug:
    msg: "The main coder EC2 instance is available with ID='{{ coder_ec2_instance_id }}'"
  when:
    - coder_ec2_instance_id != "N/A"

- name: Stop the main coder EC2 instance (if required)
  amazon.aws.ec2:
    instance_ids:
      - "{{ coder_ec2_instance_id}}"
    state: stopped
    wait: true
    wait_timeout: 500
  when:
    - coder_ec2_instance_id != "N/A"

- name: Create an AMI from the main coder EC2 instance
  amazon.aws.ec2_ami:
    instance_id: "{{ coder_ec2_instance_id}}"
    wait: yes
    name: "{{ aws_ec2_image_name }}"
    description: Main coder latest snapshot
    tags:
      Name: "{{ aws_ec2_image_name }}"
      module: coder
  register: coder_ec2_latest_image
  when:
    - coder_ec2_instance_id != "N/A"

- name: Get the existing main coder AMI
  set_fact: old_coder_ec2_image="{{ lookup('aws_ssm', '{{ aws_ssm_path }}/state/coder_ec2_image') | default('N/A', true) }}"

- name: Save the main coder latest image ID to parameter store
  community.aws.aws_ssm_parameter_store:
    name: "{{ aws_ssm_path }}/state/coder_ec2_image"
    description: "The main coder latest image"
    value: "{{ coder_ec2_latest_image.image_id }}"
  when:
    - coder_ec2_instance_id != "N/A"

- name: Destroy outdated main coder AMI
  amazon.aws.ec2_ami:
    image_id: "{{ old_coder_ec2_image }}"
    delete_snapshot: True
    state: absent
  when:
    - coder_ec2_instance_id != "N/A"
    - old_coder_ec2_image != "N/A"

- name: Destroy the main coder EC2 instance
  amazon.aws.ec2:
    instance_ids:
      - "{{ coder_ec2_instance_id}}"
    state: absent
  when:
    - coder_ec2_instance_id != "N/A"

- name: Delete the main coder EC2 instance ID parameter store key
  community.aws.aws_ssm_parameter_store:
    name: "{{ aws_ssm_path }}/state/coder_ec2_instance.id"
    state: absent
