---
#------------------------------------------------------------
# Setup Basic Auth
#------------------------------------------------------------

- name: Install passlib from pip
  pip:
    name: passlib==1.7.2

- name: Setup basic auth password for the main server
  htpasswd:
    path: "/etc/nginx/htpasswd/{{ server_domain }}"
    name: "{{ auth_username }}"
    password: "{{ auth_password }}"
    owner: root
    group: www-data
    mode: 0644
