---
#------------------------------------------------------------
# Install Docker
#------------------------------------------------------------

- name: Install Docker prerequisites
  apt:
    name: apt-transport-https, ca-certificates, curl, software-properties-common
    state: latest
    update_cache: yes

- name: Ensure docker is at the latest version
  apt:
    name: docker.io, docker-compose
    state: present
    update_cache: yes

- name: Make sure that Docker service is running
  systemd:
    state: started
    name: docker

- name: Allow the main user to run docker without sudo
  user:
    name: "{{ linux_user }}"
    groups: docker
    append: yes

#------------------------------------------------------------
# Install additional dependencies
#------------------------------------------------------------

- name: Install additional dependencies
  apt:
    name: git, python3-pip, python-is-python3, supervisor, apache2-utils
    state: latest
    update_cache: yes

- name: Make sure that supervisord service is running
  systemd:
    state: started
    name: supervisor
