---
#------------------------------------------------------------
# Start iHaskell Jupyter notebook
#------------------------------------------------------------

- name: Start iHaskell Jupyter notebook
  docker_compose:
    project_src: "{{ coder_apps_work_dir }}"
    services: ihaskell-notebook
    state: present
  register: output
