---
#------------------------------------------------------------
# Start iHaskell Jupyter notebook
#------------------------------------------------------------

- name: Start iHaskell Jupyter notebook
  docker_compose:
    project_src: "{{ coder_apps_work_dir }}"
    files: ihaskell-compose.yaml
    state: present
  register: output
