---
#------------------------------------------------------------
# Setup iHaskell Jupyter notebook
#------------------------------------------------------------

- name: Setup iHaskell Jupyter notebook
  docker_compose:
    project_src: "{{ coder_apps_work_dir }}"
    files: ihaskell-compose.yaml
    state: "{{ ihaskell }}"
    restarted: yes
  register: output
