---
#------------------------------------------------------------
# Setup iHaskell Jupyter notebook
#------------------------------------------------------------

- name: Setup basic auth password for iHaskell
  htpasswd:
    path: "/etc/nginx/htpasswd/{{ ihaskell_domain }}"
    name: "{{ auth_username }}"
    password: "{{ auth_password }}"
    owner: root
    group: www-data
    mode: 0644

- name: Create iHaskell service
  template:
    src: "../templates/ihaskell.service"
    dest: /etc/systemd/system/ihaskell.service
  notify:
  - Restart iHaskell service

- name: Enable iHaskell service
  service:
    name: ihaskell
    enabled: yes

- name: Make shure that iHaskell service is running
  service:
    state: started
    name: ihaskell
