---
#------------------------------------------------------------
# Remove a DigitalOcean Resources
#------------------------------------------------------------

- name: Remove coder droplet
  digital_ocean_droplet:
    state: absent
    unique_name: yes
    name: "{{ do_droplet_name }}"
    oauth_token: "{{ do_api_token }}"
